select * from mytable limit 20;

# q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from mytable
group by gender;

# q2. which customers used a discount but still spent more than the avg purchase amount?
select customer_id, purchase_amount
from mytable
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from mytable);

# q3. which are the top 5 products with the highest avg review rating?
select item_purchased, round(avg(review_rating),2) as "avg product rating"
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;

# q4. compare the avg purchase amounts between standard and express shipping
select shipping_type, avg(purchase_amount)
from mytable
where shipping_type in ('Standard', 'Express')
group by  shipping_type;

# q5. Do subscribed customers spend more? compare avg spend and total revenue btwn subscribers and non-subscribers
select subscription_status, count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from mytable
group by subscription_status
order by total_revenue, avg_spend desc;

# q6. which 5 products have the highest % of purchases with discounts applied?
select item_purchased, 
round(100* sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) , 2) as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;

# q7. segment customers into new, returning, and loyal based on their total num of prev purchases, and show the count of each segment
with customer_type as(
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from mytable
)
select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment;

# q8. what are the top 3 most purchased products within each category?
with item_counts as (
select category, item_purchased, count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id)desc) as item_rank
from mytable
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

# q9. Are customers who are repeat buyers (more than 5 prev purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from mytable
where previous_purchases > 5
group by subscription_status;

# q10. what is the revenue contribution of each age group
select age_group, sum(purchase_amount) as total_revenue
from mytable
group by age_group
order by total_revenue desc;

